### ISSUE TITLE
LOR sample image needs to be improved

### ISSUE THREAD

**Issue by tursics** [berlinonline/open-data-handbuch#1]
Das LOR-Beispiel: https://github.com/berlinonline/open-data-handbuch/blob/master/images/format-example-tree.png enthält einen Fehler. In der rechten Spalte ist die Nummerierung falsch. Entweder lauter die LOR von Hasenheide 08010101 oder Hasenheide hat die Nummer 15. Entsprechend die drei Einträge darunter auch.

**Comment by knudmoeller** [comment]
Argh, das war ein Flüchtigkeitsfehler. Hasenheide hat den Schlüssel `15`. Wird gefixt!

**Comment by knudmoeller** [comment]
Jetzt sind die korrekten Schlüssel in der Grafik: https://berlinonline.github.io/open-data-handbuch/#baumstruktur-hierarchische-daten
