### ISSUE TITLE
Link zur Strategie ist kaputt

### ISSUE THREAD

**Issue by hejjoe** [berlinonline/open-data-handbuch#3]
Der zweifach genutzte Link zum PDF der Berliner Open Data Strategie von 2011 ist kaputt ([1](https://github.com/berlinonline/open-data-handbuch/blame/master/index.md#L5), [2](https://github.com/berlinonline/open-data-handbuch/blame/master/index.md#L1660)). Entweder die PDF-Datei ist innerhalb von Imperia umgezogen (und somit dort neu verlinkbar) oder der Permalink von Fraunhofer sollte genutzt werden.

kaputter Link: 

`https://www.berlin.de/sen/inneres/service/publikationen/strategie-studie_zur_umsetzung_des_open-data-gedankens_in_der___ffentlichen_verwaltung.pdf`

Permalink: 

`https://nbn-resolving.org/urn:nbn:de:0011-n-1955071`

**Comment by knudmoeller** [comment]
Danke für den Hinweis! Der Permalink von der DNB ist sehr gut, habe ihn eingesetzt. Gibt jetzt eine neue Version: https://github.com/berlinonline/open-data-handbuch/blob/master/CHANGELOG.md#1010
